CTDA-1669: Add metrics in the PPNS connector, fraction of posted messages that have boxes attached
hmrc/transit-movements-trader-at-destination pull request #284
Opened 2022-01-31 13:30 UTC by drnaylor

Thoughts:

* ~~I suspect what we're interested in is the ratio of calls to getBox vs sendPushNotification over the entire lifetime of the application. In this case, a ratio of two counters is what we want. However, if we want it over a rolling time period, we might be able to do this with Meters.~~
* ~~Do we just want a ratio of calls to these methods, or do we want a ratio of _successful_ calls? My interpretation is the former, but if it's the latter, should be easy to do.~~

Departures will follow once we're happy with this.

---

This has been through a lot of iterations, we settled on the fraction of submitted arrivals that have a box attached. We also have a week sliding window for this data.

2022-01-31 13:55 UTC, RobertLaverick approved these changes

2022-02-01 11:39 UTC, drnaylor-oc commented
The two commits in this PR at this stage should be considered as two separate solutions.

2022-02-17 11:36 UTC, RobertLaverick approved these changes

2022-03-02 14:27 UTC, RobertLaverick commented
test me again

2022-03-02 14:29 UTC, RobertLaverick commented
retest this please

2022-03-14 09:57 UTC, drnaylor-oc commented
retest

2022-03-16 16:06 UTC, RobertLaverick requested changes

2022-03-16 16:06 UTC, RobertLaverick commented on app/audit/AuditDetails.scala
> +case class AuthenticatedAuditDetails(channel: ChannelType, enrolmentId: Ior[TURN, EORINumber], json: JsObject, boxId: Option[BoxId]) extends AuditDetails {
have you considered having boxId default to None?
`boxId: Option[BoxId] = None`

2022-03-23 13:37 UTC, RobertLaverick approved these changes

2022-03-23 14:55 UTC, merged